import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function Navbar() {
  return (
    <nav className="relative px-4 py-4 flex justify-between items-center bg-white">
      
      <ul className="hidden absolute top-1/2 left-1/2 transform -translate-y-1/2 -translate-x-1/2 lg:flex lg:mx-auto lg:flex lg:items-center lg:w-auto lg:space-x-6">
        <li><a className="text-sm text-gray-400 hover:text-gray-500" href="/">Zum Warzenhof</a></li>
        <li><a className="text-sm text-gray-400 hover:text-gray-500" href="/menu">Essna + Trinkna</a></li>
      </ul>
    </nav>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  )
}
